<?php

namespace Database\Seeders\BeautyProduct;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\{Storage, File};
use Illuminate\Support\Facades\DB;

class CustomBannerSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {
    DB::table('custom_banners')->truncate();
    $this->bannerSeeding();
    $this->uploadBannerImages();
  }

  private function bannerSeeding()
  {

    $hover3CardSkus = DB::table('product_variants')
      ->inRandomOrder()
      ->limit(15)
      ->pluck('sku');

    $url = env('APP_URL');
    $now = date('Y-m-d H:i:s');

    $banners1 = [
      // Ticker Banners
      [
        'id' => 1,
        'title' => 'Dining Tables Starting at $199',
        'position' => 'ticker',
        'settings' => ['speed' => '30000', 'hyper_link' => "$url/product/{$hover3CardSkus[0]}"],
        'custom_order' => 6,
      ],
      [
        'id' => 2,
        'title' => 'Limited Time Offer: Free Throw Pillows with Sofa Purchases',
        'position' => 'ticker',
        'settings' => ['speed' => '30000', 'hyper_link' => "$url/product/{$hover3CardSkus[1]}"],
        'custom_order' => 5,
      ],
      [
        'id' => 3,
        'title' => 'Free Shipping on Orders Over $300',
        'position' => 'ticker',
        'settings' => ['speed' => '30000', 'hyper_link' => "$url/product/{$hover3CardSkus[2]}"],
        'custom_order' => 2,
        'deleted_at' => '2025-05-30 01:18:09',
      ],
      [
        'id' => 4,
        'title' => 'Dining Tables Starting at $399',
        'position' => 'ticker',
        'settings' => ['speed' => '5000', 'hyper_link' => "$url/product/{$hover3CardSkus[3]}"],
        'custom_order' => 4,
      ],
      [
        'id' => 5,
        'title' => 'Free Shipping on Orders Over $200',
        'position' => 'ticker',
        'settings' => ['speed' => '5000', 'hyper_link' => "$url/product/{$hover3CardSkus[4]}"],
        'custom_order' => 3,
      ],
      [
        'id' => 6,
        'title' => 'Limited Time Offer: Free Throw Pillows with Sofa Purchases',
        'position' => 'ticker',
        'settings' => ['speed' => '5000', 'hyper_link' => "$url/product/{$hover3CardSkus[5]}"],
        'custom_order' => 2,
      ],
      [
        'id' => 7,
        'title' => 'Free Shipping on Orders Over $300',
        'position' => 'ticker',
        'settings' => ['speed' => '30000', 'hyper_link' => "$url/product/{$hover3CardSkus[6]}"],
        'custom_order' => 1,
      ],
      // Hero Banners
      [
        'id' => 8,
        'title' => 'Hero Slider 1',
        'position' => 'hero',
        'settings' => [
          'image' => 'homeslider1.webp',
          'content' => '<p>Comfort Meets Style<br>in Every Corner of Your Home</p>',
          'alt_text' => 'ssdas',
          'hyper_link' => "$url/product/{$hover3CardSkus[7]}",
          'default_image_size' => null,
        ],
        'custom_order' => 1,
      ],
      [
        'id' => 9,
        'title' => 'Hero Slider 2',
        'position' => 'hero',
        'settings' => [
          'image' => 'homeslider2.webp',
          'content' => '<p>Limited-Time Deal:<br>Up to 40% Off on Sofas</p>',
          'alt_text' => 'alt text',
          'hyper_link' => "$url/product/{$hover3CardSkus[8]}",
          'default_image_size' => null,
        ],
        'custom_order' => 5,
      ],
      [
        'id' => 10,
        'title' => 'Hero Slider 3',
        'position' => 'hero',
        'settings' => [
          'image' => 'homeslider3.webp',
          'content' => '<p>Exclusive Deal:<br>Up to 30% Off on Chairs - Limited Time Only!</p>',
          'alt_text' => null,
          'hyper_link' => "$url/product/{$hover3CardSkus[9]}",
          'default_image_size' => null,
        ],
        'custom_order' => 27,
      ],
      // Hover Card Banners
      [
        'id' => 11,
        'title' => 'Left Hover Card',
        'position' => 'hover_card',
        'settings' => [
          'image' => 'category_threeblocks_th1.webp',
          'content' => '<h4 class="font16 fw-normal text-center mb-0">New Arrival</h4><h3 class="font35 fw-normal text-center">Chair</h3>',
          'alt_text' => 'ssdas',
          'btn_text' => 'View',
          'btn_color' => '#42388f',
          'hyper_link' => null,
          'product_sku' => $hover3CardSkus[10],
          'default_image_size' => null,
        ],
        'custom_order' => 6,
      ],
      [
        'id' => 12,
        'title' => 'Middle Hover Card',
        'position' => 'hover_card',
        'settings' => [
          'image' => 'category_threeblocks_th2.webp',
          'content' => '<div class="top flow-rootx2 c--blackc"><h4 class="font14 fw-normal text-center mb-0">New Arrival</h4><h3 class="font30 fw-normal text-center">Chair</h3></div><div class="pricebox font20 text-center"><span>$</span>750.00</div>',
          'alt_text' => 'alt',
          'btn_text' => 'View',
          'btn_color' => '#000000',
          'hyper_link' => null,
          'product_sku' => $hover3CardSkus[11],
          'default_image_size' => null,
        ],
        'custom_order' => 8,
      ],
      [
        'id' => 13,
        'title' => 'Right Hover Card',
        'position' => 'hover_card',
        'settings' => [
          'image' => 'category_threeblocks_th3.webp',
          'content' => '<h4 class="font16 fw-normal text-center mb-0">New Arrival</h4><h3 class="font35 fw-normal text-center">Chair</h3>',
          'alt_text' => 'alt',
          'btn_text' => 'View',
          'btn_color' => '#000000',
          'hyper_link' => null,
          'product_sku' => $hover3CardSkus[12],
          'default_image_size' => null,
        ],
        'custom_order' => 9,
      ],
      // Block Wrap Banner
      [
        'id' => 14,
        'title' => 'Block Wrap',
        'position' => 'block_wrap',
        'settings' => [
          'image' => 'sleek-furniture.webp',
          'content' => '<p>Blending sleek, contemporary design with artistic forms, our collection enhances every space with sophistication and comfort.</p>',
          'alt_text' => 'alt',
          'btn_text' => 'View All Collections',
          'btn_color' => '#000000',
          'hyper_link' => "$url/categories",
          'default_image_size' => null,
        ],
        'custom_order' => 10,
      ],
      // Brand Carousel Banners
      [
        'id' => 15,
        'title' => 'Brand Carousel 1',
        'position' => 'brand_carousel',
        'settings' => ['image' => 'brandlogo1.webp', 'alt_text' => 'alt text', 'default_image_size' => null],
        'custom_order' => 11,
      ],
      [
        'id' => 16,
        'title' => 'Brand Carousel 2',
        'position' => 'brand_carousel',
        'settings' => ['image' => 'brandlogo2.webp', 'alt_text' => 'alt', 'default_image_size' => null],
        'custom_order' => 12,
      ],
      [
        'id' => 17,
        'title' => 'Brand Carousel 3',
        'position' => 'brand_carousel',
        'settings' => ['image' => 'brandlogo3.webp', 'alt_text' => null, 'default_image_size' => null],
        'custom_order' => 13,
      ],
      [
        'id' => 18,
        'title' => 'Brand Carousel 4',
        'position' => 'brand_carousel',
        'settings' => ['image' => 'brandlogo4.webp', 'alt_text' => null, 'default_image_size' => null],
        'custom_order' => 14,
      ],
      [
        'id' => 19,
        'title' => 'Brand Carousel 5',
        'position' => 'brand_carousel',
        'settings' => ['image' => 'brandlogo5.webp', 'alt_text' => null, 'default_image_size' => null],
        'custom_order' => 15,
      ],
      [
        'id' => 20,
        'title' => 'Brand Carousel 6',
        'position' => 'brand_carousel',
        'settings' => ['image' => 'brandlogo6.webp', 'alt_text' => null, 'default_image_size' => null],
        'custom_order' => 16,
      ],
    ];

    foreach ($banners1 as $banner) {
      DB::table('custom_banners')->insert([
        'id' => $banner['id'],
        'title' => $banner['title'],
        'position' => $banner['position'],
        'settings' => json_encode($banner['settings']),
        'custom_order' => $banner['custom_order'],
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => $banner['deleted_at'] ?? null,
      ]);
    }


    $banners2 = [
      // Brand Carousel Banners
      [
        'id' => 21,
        'title' => 'Brand Carousel 7',
        'position' => 'brand_carousel',
        'settings' => ['image' => 'brandlogo7.webp', 'alt_text' => null, 'default_image_size' => null],
        'custom_order' => 17,
      ],
      [
        'id' => 22,
        'title' => 'Brand Carousel 8',
        'position' => 'brand_carousel',
        'settings' => ['image' => 'brandlogo3.webp', 'alt_text' => 'alt', 'default_image_size' => null],
        'custom_order' => 18,
      ],
      [
        'id' => 23,
        'title' => 'Brand Carousel 9',
        'position' => 'brand_carousel',
        'settings' => ['image' => 'brandlogo1.webp', 'alt_text' => null, 'default_image_size' => null],
        'custom_order' => 28,
      ],
      [
        'id' => 24,
        'title' => 'Brand Carousel 10',
        'position' => 'brand_carousel',
        'settings' => ['image' => 'brandlogo2.webp', 'alt_text' => null, 'default_image_size' => null],
        'custom_order' => 29,
      ],
      // Four Hover Cards
      [
        'id' => 25,
        'title' => 'Furniture Contemporary 1',
        'position' => 'four_hover_cards',
        'settings' => [
          'image' => 'contemporary1.webp',
          'content' => '<p>Luxe Comfort Haven</p>',
          'alt_text' => 'alt text',
          'btn_text' => 'View',
          'btn_color' => '#000000',
          'hyper_link' => null,
          'default_image_size' => null,
        ],
        'custom_order' => 30,
      ],
      [
        'id' => 26,
        'title' => 'Furniture Contemporary 2',
        'position' => 'four_hover_cards',
        'settings' => [
          'image' => 'contemporary2.webp',
          'content' => '<p>Luxe Comfort Haven</p>',
          'alt_text' => 'alt text',
          'btn_text' => 'View',
          'btn_color' => '#000000',
          'hyper_link' => null,
          'default_image_size' => null,
        ],
        'custom_order' => 31,
      ],
      [
        'id' => 27,
        'title' => 'Furniture Contemporary 3',
        'position' => 'four_hover_cards',
        'settings' => [
          'image' => 'contemporary4.webp',
          'content' => '<p>Luxe Comfort Haven</p>',
          'alt_text' => 'alt text',
          'btn_text' => null,
          'btn_color' => '#000000',
          'hyper_link' => null,
          'default_image_size' => null,
        ],
        'custom_order' => 32,
      ],
      [
        'id' => 28,
        'title' => 'Furniture Contemporary 4',
        'position' => 'four_hover_cards',
        'settings' => [
          'image' => 'contemporary5.webp',
          'content' => '<p>Luxe Comfort Haven</p>',
          'alt_text' => 'alt text',
          'btn_text' => 'View',
          'btn_color' => '#000000',
          'hyper_link' => null,
          'default_image_size' => null,
        ],
        'custom_order' => 33,
      ],
      // Sale Block Fullwidth
      [
        'id' => 29,
        'title' => 'Mayuri Made Beautiful with Functional Elegance',
        'position' => 'sale_block_fullwidth',
        'settings' => [
          'image' => 'sales_block_img.webp',
          'content' => '<div class="blk"><h2 class="fw-normal c--whitec font80 m-0">SALE</h2><h4 class="fw-normal c--whitec font25">Up to 50% Off</h4></div>',
          'alt_text' => null,
          'btn_text' => 'View Collections',
          'btn_color' => '#000000',
          'hyper_link' => "$url/categories",
          'default_image_size' => null,
        ],
        'custom_order' => 34,
      ],
      // Flow Banner
      [
        'id' => 30,
        'title' => 'Keep It Flowing',
        'position' => 'flow_banner',
        'settings' => [
          'image' => 'furniture_keepflowing.webp',
          'content' => '<p><span>Keep</span> <span>It</span> <span>Flowing</span></p>',
          'alt_text' => 'alt text',
          'default_image_size' => null,
        ],
        'custom_order' => 35,
      ],
      // Subscribe Banner
      [
        'id' => 31,
        'title' => 'Subscribe',
        'position' => 'subscribe_banner',
        'settings' => [
          'content' => '<p>Subscribe now and save up to 15% on selected orders! Find furniture that perfectly suits your style.</p>',
        ],
        'custom_order' => 36,
      ],
      // Shop Page Banner
      [
        'id' => 32,
        'title' => 'Shop Page',
        'position' => 'shop_page_banner',
        'settings' => [
          'image' => 'product-hero.webp',
          'default_image_size' => null,
          'alt_text' => null,
        ],
        'custom_order' => 6,
        'created_by' => 6,
        'updated_by' => 6,
      ],
      // Category Page Banner
      [
        'id' => 33,
        'title' => 'Crafted with Innovation',
        'position' => 'category_page_banner',
        'settings' => [
          'image' => 'category_hero.webp',
          'default_image_size' => null,
          'alt_text' => null,
          'content' => '<p class="act font25" data-parallax-strength-vertical="-2.5" data-parallax-height="-2.5"><span data-parallax-target="">Our sofas are durable, simple to assemble,</span><br><span data-parallax-target="">and adaptable to your evolving needs.</span></p>',
        ],
        'custom_order' => 6,
        'created_by' => 6,
        'updated_by' => 6,
      ],
      // Hot Deals Category Banners
      [
        'id' => 34,
        'title' => 'Hot Deal 1',
        'position' => 'hot_deals_category_banner',
        'settings' => [
          'image' => 'hot_deals1.webp',
          'default_image_size' => null,
          'alt_text' => '#',
          'hyper_link' => 'https://www.google.com',
        ],
        'custom_order' => 6,
        'created_by' => 6,
        'updated_by' => 6,
      ],
      [
        'id' => 35,
        'title' => 'Hot Deal 2',
        'position' => 'hot_deals_category_banner',
        'settings' => [
          'image' => 'hot_deals2.webp',
          'default_image_size' => null,
          'alt_text' => null,
          'hyper_link' => null,
        ],
        'custom_order' => 6,
        'created_by' => 6,
        'updated_by' => 6,
      ],
      [
        'id' => 36,
        'title' => 'Hot Deal 3',
        'position' => 'hot_deals_category_banner',
        'settings' => [
          'image' => 'hot_deals3.webp',
          'default_image_size' => null,
          'alt_text' => null,
          'hyper_link' => 'https://www.google.com',
        ],
        'custom_order' => 6,
        'created_by' => 6,
        'updated_by' => 6,
      ],
      [
        'id' => 37,
        'title' => 'Hot Deal 4',
        'position' => 'hot_deals_category_banner',
        'settings' => [
          'image' => 'hot_deals4.webp',
          'default_image_size' => null,
          'alt_text' => null,
          'hyper_link' => null,
        ],
        'custom_order' => 6,
        'created_by' => 6,
        'updated_by' => 6,
      ],
      // Category Sale Block
      [
        'id' => 38,
        'title' => 'Mayuri Made Beautiful with Functional Elegance',
        'position' => 'category_sale_block',
        'settings' => [
          'image' => 'sales_block_img2.webp',
          'default_image_size' => null,
          'alt_text' => null,
          'content' => '<div class="blk"><h2 class="fw-normal c--whitec font80 m-0">SALE</h2><h4 class="fw-normal c--whitec font25">Up to 50% Off</h4></div>',
          'btn_text' => 'View Collections',
          'btn_color' => '#000000',
          'hyper_link' => "$url/categories",
        ],
        'custom_order' => 6,
        'created_by' => 6,
        'updated_by' => 6,
      ],
      // Login Page Banner
      [
        'id' => 39,
        'title' => 'Luxury',
        'position' => 'login_page_banner',
        'settings' => [
          'image' => 'signup_popup_thumb.webp',
          'default_image_size' => null,
          'alt_text' => null,
          'content' => '<p>Discover 30k+ varieties</p>',
        ],
        'custom_order' => 6,
        'created_by' => 6,
        'updated_by' => 6,
      ],
      // Category Page Headline Banner
      [
        'id' => 40,
        'title' => 'Ingenious Design Meets Lasting Durability',
        'position' => 'category_page_headline_banner',
        'settings' => [],
        'custom_order' => 6,
        'created_by' => 6,
        'updated_by' => 6,
      ],
    ];

    foreach ($banners2 as $banner) {
      DB::table('custom_banners')->insert([
        'id' => $banner['id'],
        'title' => $banner['title'],
        'position' => $banner['position'],
        'settings' => json_encode($banner['settings']),
        'custom_order' => $banner['custom_order'],
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => $banner['deleted_at'] ?? null,
        'created_by' => $banner['created_by'] ?? null,
        'updated_by' => $banner['updated_by'] ?? null,
        'deleted_by' => $banner['deleted_by'] ?? null,
      ]);
    }

    /* $data1 = [
      [
        'id' => 1,
        'title' => 'Dining Tables starting at $199',
        'position' => 'ticker',
        'settings' => '{"speed":"30000","hyper_link":"' . $url . '/product/' . $hover3CardSkus[0] . '"}',
        'custom_order' => 6,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 2,
        'title' => 'Limited Time Offer: Free throw pillows with sofa purchases',
        'position' => 'ticker',
        'settings' => '{"speed":"30000","hyper_link":"' . $url . '/product/' . $hover3CardSkus[1] . '"}',
        'custom_order' => 5,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 3,
        'title' => 'Free Shipping on orders over $300',
        'position' => 'ticker',
        'settings' => '{"speed":"30000","hyper_link":"' . $url . '/product/' . $hover3CardSkus[2] . '"}',
        'custom_order' => 2,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => '2025-05-30 01:18:09',
      ],
      [
        'id' => 4,
        'title' => 'Dining Tables starting at $399',
        'position' => 'ticker',
        'settings' => '{"speed":"5000","hyper_link":"' . $url . '/product/' . $hover3CardSkus[3] . '"}',
        'custom_order' => 4,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 5,
        'title' => 'Free Shipping on orders over $200',
        'position' => 'ticker',
        'settings' => '{"speed":"5000","hyper_link":"' . $url . '/product/' . $hover3CardSkus[4] . '"}',
        'custom_order' => 3,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 6,
        'title' => 'Limited Time Offer: Free throw pillows with sofa purchases',
        'position' => 'ticker',
        'settings' => '{"speed":"5000","hyper_link":"' . $url . '/product/' . $hover3CardSkus[5] . '"}',
        'custom_order' => 2,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 7,
        'title' => 'Free Shipping on orders over $300',
        'position' => 'ticker',
        'settings' => '{"speed":"30000","hyper_link":"' . $url . '/product/' . $hover3CardSkus[6] . '"}',
        'custom_order' => 1,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 8,
        'title' => 'Hero Slider 1',
        'position' => 'hero',
        'settings' => '{"image":"homeslider1.webp","content":"<p>Comfort Meets Style<br>in Every Corner of Your Home</p>","alt_text":"ssdas","hyper_link":"' . $url . '/product/' . $hover3CardSkus[7] . '","default_image_size":null}',
        'custom_order' => 1,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 9,
        'title' => 'Hero Slider 2',
        'position' => 'hero',
        'settings' => '{"image":"homeslider2.webp","content":"<p>Limited-Time Deal:<br>Up to 40% Off on Sofas</p>","alt_text":"alt text","hyper_link":"' . $url . '/product/' . $hover3CardSkus[8] . '","default_image_size":null}',
        'custom_order' => 5,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 10,
        'title' => 'Hero Slider 3',
        'position' => 'hero',
        'settings' => '{"image":"homeslider3.webp","content":"<p>Exclusive Deal:<br>Up to 30% Off on Chairs - Limited Time Only!</p>","alt_text":null,"hyper_link":"' . $url . '/product/' . $hover3CardSkus[9] . '","default_image_size":null}',
        'custom_order' => 27,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 11,
        'title' => 'Left Hover Card',
        'position' => 'hover_card',
        'settings' => '{"image": "category_threeblocks_th1.webp", "content": "<h4 class=\"font16 fw-normal text-center mb-0\">New Arrival</h4><h3 class=\"font35 fw-normal text-center\">Chair</h3>", "alt_text": "ssdas", "btn_text": "View", "btn_color": "#42388f", "hyper_link": null, "product_sku": "' . $hover3CardSkus[10] . '", "default_image_size": null}',
        'custom_order' => 6,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 12,
        'title' => 'Hover card Middle',
        'position' => 'hover_card',
        'settings' => '{"image": "category_threeblocks_th2.webp", "content": "<div class=\"top flow-rootx2 c--blackc\"><h4 class=\"font14 fw-normal text-center mb-0\">New Arrival</h4><h3 class=\"font30 fw-normal text-center\">Chair</h3></div><div class=\"pricebox font20 text-center\"><span>$</span>750.00</div>", "alt_text": "alt", "btn_text": "View", "btn_color": "#000000", "hyper_link": null, "product_sku": "' . $hover3CardSkus[11] . '", "default_image_size": null}',
        'custom_order' => 8,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 13,
        'title' => 'Hover Right',
        'position' => 'hover_card',
        'settings' => '{"image": "category_threeblocks_th3.webp", "content": "<h4 class=\"font16 fw-normal text-center mb-0\">New Arrival</h4><h3 class=\"font35 fw-normal text-center\">Chair</h3>", "alt_text": "alt", "btn_text": "View", "btn_color": "#000000", "hyper_link": null, "product_sku": "' . $hover3CardSkus[12] . '", "default_image_size": null}',
        'custom_order' => 9,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 14,
        'title' => 'Block Wrap',
        'position' => 'block_wrap',
        'settings' => '{"image": "sleek-furniture.webp", "content": "<p>Blending sleek, contemporary design with artistic forms, our collection enhances every space with sophistication and comfort.</p>", "alt_text": "alt", "btn_text": "View All Collections", "btn_color": "#000000", "hyper_link": "' . $url . '/categories' . '", "default_image_size": null}',
        'custom_order' => 10,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
    ];

    DB::table('custom_banners')->insert($data1);

    $data2 = [
      [
        'id' => 15,
        'title' => 'Brand Caraosal 1',
        'position' => 'brand_carousel',
        'settings' => '{"image": "brandlogo1.webp", "alt_text": "alt text", "default_image_size": null}',
        'custom_order' => 11,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 16,
        'title' => 'Brand Caraosal 2',
        'position' => 'brand_carousel',
        'settings' => '{"image": "brandlogo2.webp", "alt_text": "alt", "default_image_size": null}',
        'custom_order' => 12,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 17,
        'title' => 'Brand Caraosal 3',
        'position' => 'brand_carousel',
        'settings' => '{"image": "brandlogo3.webp", "alt_text": null, "default_image_size": null}',
        'custom_order' => 13,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 18,
        'title' => 'Brand Caraosal 4',
        'position' => 'brand_carousel',
        'settings' => '{"image": "brandlogo4.webp", "alt_text": null, "default_image_size": null}',
        'custom_order' => 14,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 19,
        'title' => 'Brand Caraosal 5',
        'position' => 'brand_carousel',
        'settings' => '{"image": "brandlogo5.webp", "alt_text": null, "default_image_size": null}',
        'custom_order' => 15,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 20,
        'title' => 'Brand Caraosal 6',
        'position' => 'brand_carousel',
        'settings' => '{"image": "brandlogo6.webp", "alt_text": null, "default_image_size": null}',
        'custom_order' => 16,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 21,
        'title' => 'Brand Caraosal 7',
        'position' => 'brand_carousel',
        'settings' => '{"image": "brandlogo7.webp", "alt_text": null, "default_image_size": null}',
        'custom_order' => 17,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 22,
        'title' => 'Brand Caraosal 8',
        'position' => 'brand_carousel',
        'settings' => '{"image": "brandlogo3.webp", "alt_text": "alt", "default_image_size": null}',
        'custom_order' => 18,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 23,
        'title' => 'Brand Carousel 9',
        'position' => 'brand_carousel',
        'settings' => '{"image": "brandlogo1.webp", "alt_text": null, "default_image_size": null}',
        'custom_order' => 28,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 24,
        'title' => 'Brand Carousel 10',
        'position' => 'brand_carousel',
        'settings' => '{"image": "brandlogo2.webp", "alt_text": null, "default_image_size": null}',
        'custom_order' => 29,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 25,
        'title' => 'Furniture contemporary 1',
        'position' => 'four_hover_cards',
        'settings' => '{"image": "contemporary1.webp", "content": "<p>Luxe Comfort Haven</p>", "alt_text": "alt text", "btn_text": "View", "btn_color": "#000000", "hyper_link": null, "default_image_size": null}',
        'custom_order' => 30,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 26,
        'title' => 'Furniture contemporary 2',
        'position' => 'four_hover_cards',
        'settings' => '{"image": "contemporary2.webp", "content": "<p>Luxe Comfort Haven</p>", "alt_text": "alt text", "btn_text": "View", "btn_color": "#000000", "hyper_link": null, "default_image_size": null}',
        'custom_order' => 31,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 27,
        'title' => 'Furniture contemporary 3',
        'position' => 'four_hover_cards',
        'settings' => '{"image": "contemporary4.webp", "content": "<p>Luxe Comfort Haven</p>", "alt_text": "alt text", "btn_text": null, "btn_color": "#000000", "hyper_link": null, "default_image_size": null}',
        'custom_order' => 32,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 28,
        'title' => 'Furniture contemporary 4',
        'position' => 'four_hover_cards',
        'settings' => '{"image": "contemporary5.webp", "content": "<p>Luxe Comfort Haven</p>", "alt_text": "alt text", "btn_text": "View", "btn_color": "#000000", "hyper_link": null, "default_image_size": null}',
        'custom_order' => 33,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 29,
        'title' => 'Mayuri Made Beautiful with Functional Elegance',
        'position' => 'sale_block_fullwidth',
        'settings' => '{"image": "sales_block_img.webp", "content":"<div class=\"blk\"><h2 class=\"fw-normal c--whitec font80 m-0\">SALE</h2><h4 class=\"fw-normal c--whitec font25\">Up to 50% Off</h4></div>", "alt_text": null, "btn_text": "View Collections", "btn_color": "#000000", "hyper_link": "' . $url . '/categories' . '", "default_image_size": null}',
        'custom_order' => 34,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 30,
        'title' => 'Keep It Flowing',
        'position' => 'flow_banner',
        'settings' => '{"image": "furniture__keepfrowing.webp", "content": "<p><span>Keep</span> <span>It</span> <span>Flowing</span></p>", "alt_text": "alt text", "default_image_size": null}',
        'custom_order' => 35,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 31,
        'title' => 'Subscribe',
        'position' => 'subscribe_banner',
        'settings' => '{"content": "<p>Subscribe now and save up to 15% on selected orders! Find furniture that perfectly suits your style.</p>"}',
        'custom_order' => 36,
        'created_by' => null,
        'updated_by' => null,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],

      [
        'id' => 32,
        'title' => 'Shop Page',
        'position' => 'shop_page_banner',
        'settings' => '{"image":"product-hero.webp","default_image_size":null,"alt_text":null}',
        'custom_order' => 6,
        'created_by' => 6,
        'updated_by' => 6,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 33,
        'title' => 'Crafted with innovation',
        'position' => 'category_page_banner',
        'settings' => json_encode(['image' => 'category_hero.webp', 'default_image_size' => null, 'alt_text' => null, 'content' => '<p class="act font25" data-parallax-strength-vertical="-2.5" data-parallax-height="-2.5"><span data-parallax-target="">Our sofas are durable, simple to assemble,</span><br><span data-parallax-target="">and adaptable to your evolving needs.</span></p>']),
        'custom_order' => 6,
        'created_by' => 6,
        'updated_by' => 6,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 34,
        'title' => 'Hotdeal 1',
        'position' => 'hot_deals_category_banner',
        'settings' => '{"image":"hot_deals1.webp","default_image_size":null,"alt_text":"#","hyper_link":"https://www.google.com"}',
        'custom_order' => 6,
        'created_by' => 6,
        'updated_by' => 6,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 35,
        'title' => 'hotdeal 2',
        'position' => 'hot_deals_category_banner',
        'settings' => '{"image":"hot_deals2.webp","default_image_size":null,"alt_text":null,"hyper_link":null}',
        'custom_order' => 6,
        'created_by' => 6,
        'updated_by' => 6,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 36,
        'title' => 'Hotdeal 3',
        'position' => 'hot_deals_category_banner',
        'settings' => '{"image":"hot_deals3.webp","default_image_size":null,"alt_text":null,"hyper_link":"https://www.google.com"}',
        'custom_order' => 6,
        'created_by' => 6,
        'updated_by' => 6,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 37,
        'title' => 'Hotdeal 4',
        'position' => 'hot_deals_category_banner',
        'settings' => '{"image":"hot_deals4.webp","default_image_size":null,"alt_text":null,"hyper_link":null}',
        'custom_order' => 6,
        'created_by' => 6,
        'updated_by' => 6,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 38,
        'title' => 'Mayuri Made Beautiful with Functional Elegance',
        'position' => 'category_sale_block',
        'settings' => '{"image":"sales_block_img2.webp","default_image_size":null,"alt_text":null,"content":"<div class=\"blk\"><h2 class=\"fw-normal c--whitec font80 m-0\">SALE</h2><h4 class=\"fw-normal c--whitec font25\">Up to 50% Off</h4></div>","btn_text":"View Collections","btn_color":"#000000","hyper_link": "' . $url . '/categories' . '"}',
        'custom_order' => 6,
        'created_by' => 6,
        'updated_by' => 6,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 39,
        'title' => 'Luxury',
        'position' => 'login_page_banner',
        'settings' => '{"image":"signup_popup_thumb.webp","default_image_size":null,"alt_text":null,"content":"<p>Discover 30k+ varities</p>"}',
        'custom_order' => 6,
        'created_by' => 6,
        'updated_by' => 6,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ],
      [
        'id' => 40,
        'title' => 'Ingenious design meets lasting durability',
        'position' => 'category_page_headline_banner',
        'settings' => '[]',
        'custom_order' => 6,
        'created_by' => 6,
        'updated_by' => 6,
        'deleted_by' => null,
        'status' => 1,
        'created_at' => $now,
        'updated_at' => $now,
        'deleted_at' => null,
      ]
    ];

    DB::table('custom_banners')->insert($data2); */
  }

  private function uploadBannerImages()
  {
    // Ensure destination directory exists
    Storage::disk('public')->makeDirectory('uploads/banners');


    $destinationPath = storage_path('app/public/uploads/banners');
    $sourcePath = public_path('SeederImages/BeautyProduct/banners');

    // Step 1: Remove all files in destination folder
    if (File::exists($destinationPath)) {
      File::deleteDirectory($destinationPath);
      Storage::disk('public')->makeDirectory('uploads/banners');
    }

    // Step 2: Copy files from source to destination
    if (File::exists($sourcePath)) {
      $files = File::files($sourcePath);

      foreach ($files as $file) {
        File::copy($file->getPathname(), $destinationPath . '/' . $file->getFilename());
      }
    }
  }
}
